### ISSUE TITLE
Number validation in Kannel!

### ISSUE THREAD

**Issue by thejvmshid** [flamencist/kannel#1]
Dear support flamencist, many respected professionals, I will immediately say that this is not a problem! We need your professional advice in configuring Kannel. Namely, the validation of the number is of interest, for example: Suppose the valid number consists of 7 digits. Which option should be used so that the number of the sender or recipient is not more than and not less than 7 digits in order to eliminate random errors. I have an assumption that it's preferable to use the white-list-regex, but I do not think up the end :) For earlier thanks for the answer and again I apologize for writing in the wrong place.

**Comment by flamencist** [comment]
Hi! I had issue.  Our mobile operator add to number specific session digits. Phone number looks like: +79102384323#1234. Kannel could not parse the number and I decided to clear all phone number's checks from source code. It was not elegant solution, but it's worked.
I think you should try to use ordinar solution for Kannel before. If it will not worked for you, you can use my solution

**Comment by thejvmshid** [comment]
flamencist, thanks for answering. I found a solution and it works perfectly. Kannel has a white-list-regex directive. Brief description of how this was achieved: With the help of this directive, in groups SMSPOKS and SMS-SERVICE indicated the format of the number. For example, in our country the number format is as follows: + 9989 [01345789] XXX-XX-XX. Those in square brackets are interconnected with the prefix number XXX. It was possible to associate each operator prefix with its corresponding code, this would be the ideal solution (with time I will do it). But in these cases the cases were simplified by the option: white-list-regex = ^(\+|00)9989\d\d\d\d\d\d\d\d$
